services:
  - type: web
    name: keepup
    runtime: python
    plan: free
    buildCommand: ./build.sh
    startCommand: ./start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    healthCheckPath: /api/stats
